# prior_month = "jul2"
# mon         =  aug1
# MON         = "aug1"
# Mon         = "aug1"
# prior_month = "aug1"
# mon         =  aug2
# MON         = "aug2"
# Mon         = "aug2"
# prior_month = "aug2"
# mon         =  sep1
# MON         = "sep1"
# Mon         = "sep1"
# prior_month = "sep1"
# mon         =  sep2
# MON         = "sep2"
# Mon         = "sep2"
# prior_month = "sep2"
# mon         =  oct1
# MON         = "oct1"
# Mon         = "oct1"
# prior_month = "oct1"
# mon         =  oct2
# MON         = "oct2"
# Mon         = "oct2"
prior_month = "oct2"
mon         =  oct2
MON         = "oct2"
Mon         = "oct2"

