Month_names = Dict(
	"mar" => "March",
	"apr" => "April",
	"may" => "May",
	"jun" => "June",
	"jul" => "July",
	"jul2" => "July-post",
	"aug1" => "early August",
	"aug2" => "late August",
	"sep1" => "early September",
	"sep2" => "late September",
	"oct1" => "early October",
	"oct2" => "late October",
	"fin" => "final polling")
